spring:
  datasource:
    url: jdbc:mysql://47.100.247.117:3306/composition?useSSL=false&useUnicode=true&characterEncoding=UTF8&useServerPrepStmts=true&prepStmtCacheSqlLimit=256&cachePrepStmts=true&prepStmtCacheSize=256&rewriteBatchedStatements=true
    username: root
    password: Lh852898625
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    generate-ddl: true